apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: capstone
  labels:
    name: api-gateway
  name: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      name: api-gateway
  template:
    metadata:
      labels:
        name: api-gateway
    spec:
      containers:
      - image: ashishrits081/api-gateway:latest
        name: api-gateway-container
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc:8761/eureka
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
