apiVersion: apps/v1
kind: Deployment
metadata:
  
  
  labels:
    name: api-gateway
  name: api-gateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      
      labels:
        name: api-gateway
    spec:
      containers:
      - image: ashishrits081/api-gateway:latest
        name: api-gateway-container
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
