apiVersion: v1
kind: Service
metadata:
  namespace: capstone
  labels:
    name: api-gateway
  name: apigatewaysvc
spec:
  type: NodePort
  ports:
  - name: "8080"
    port: 8080
    nodePort: 30036
  selector:
    name: api-gateway
status:
  loadBalancer: {}
