apiVersion: v1
kind: Service
metadata:
  labels:
    name: appointmentservice
  name: appointmentservicesvc
spec:
  type: NodePort
  ports:
  - name: "8090"
    port: 8090
    nodePort: 30037
  selector:
    name: appointmentservice
status:
  loadBalancer: {}
