apiVersion: v1
kind: Service
metadata:
  labels:
    name: appointmentservice
  name: appointmentservice
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    name: appointmentservice
status:
  loadBalancer: {}
