apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: appointmentservice
  name: appointmentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: appointmentservice
  template:
    metadata:
      labels:
        name: appointmentservice
    spec:
      containers:
      - image: ashishrits081/appointmentservice:latest
        name: appointment-service-container
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserver.default.svc.cluster.local:8761/eureka
        - name: spring.data.mongodb.uri
          value: mongodb://mongodbservice.default.svc.cluster.local:27017/fitpro
        ports:
        - containerPort: 8097
        resources: {}
      restartPolicy: Always
status: {}
