apiVersion: v1
kind: Service
metadata:
  labels:
    name: appointmentservice
  name: appointmentservice
spec:
  clusterIP: 127.0.0.1
  ports:
  - name: "8097"
    port: 8097
    targetPort: 8097
  selector:
    name: appointmentservice
status:
  loadBalancer: {}
