apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: authenticationservice
  name: authenticationservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: authenticationservice
  template:
    metadata:
      labels:
        name: authenticationservice
    spec:
      containers:
      - image: ashishrits081/authenticationservice:latest
        name: authentication-service-container
        env:
        - name: spring.datasource.url
          value: jdbc:mysql://mysqlservice.default.svc.cluster.local:3306/AuthenticationDB
        ports:
        - containerPort: 8095
        resources: {}
      restartPolicy: Always
status: {}
