apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: authenticationservice
  name: authenticationservice
spec:
  type: NodePort
  ports:
  - name: "8091"
    port: 8091
    nodePort: 30038
  selector:
    name: authenticationservice
status:
  loadBalancer: {}
