apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: authenticationservice
  name: authenticationservice
spec:
  ports:
  - name: "8091"
    port: 8091
    targetPort: 8091
  selector:
    name: authenticationservice
status:
  loadBalancer: {}
