apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: configserver
  name: configserver
spec:
  replicas: 1
  selector:
    matchLabels:
      name: configserver
  template:
    metadata:
      labels:
        name: configserver
    spec:
      containers:
      - image: ashishrits081/configserver:latest
        name: config-server-container
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: eurekaserver.default.svc.cluster.local:8761/eureka
        ports:
        - containerPort: 8888
        resources: {}
      restartPolicy: Always
status: {}
