apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: configserver
  name: configserver
spec:
  type: NodePort
  ports:
  - name: "8888"
    port: 8888
    nodePort: 30039
  selector:
    name: configserver
status:
  loadBalancer: {}
