apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: configserver
  name: configserver
spec:
  ports:
  - name: "8888"
    port: 8888
    targetPort: 8888
  selector:
    name: configserver
status:
  loadBalancer: {}
