apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: emailservice
  name: emailservice
spec:
  ports:
  - name: "8075"
    port: 8075
    targetPort: 8075
  selector:
    name: emailservice
status:
  loadBalancer: {}
