apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: emailservice
  name: emailservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: emailservice
  template:
    metadata:
      labels:
        name: emailservice
    spec:
      containers:
      - image: ashishrits081/emailservice:latest
        name: email-service-container
        env:
        - name: spring.rabbitmq.host
          value: rabbitmq.default.svc.cluster.local
        ports:
        - containerPort: 8075
        resources: {}
      restartPolicy: Always
status: {}
