apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: emailservice
  name: emailservice
spec:
  type: NodePort
  ports:
  - name: "8088"
    port: 8088
    nodePort: 30040
  selector:
    name: emailservice
status:
  loadBalancer: {}
