apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: emailservice
  name: emailservice
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    name: emailservice
status:
  loadBalancer: {}
