apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: eurekaserver
  name: eurekaserver
spec:
  type: NodePort
  ports:
  - name: "8761"
    port: 8761
    nodePort: 30041
  selector:
    name: eurekaserver
status:
  loadBalancer: {}
