apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: mongodbservice
  name: mongodbservicesvc
spec:
  type: NodePort
  ports:
  - name: "27017"
    port: 27017
    nodePort: 30042
  selector:
    name: mongodbservice
status:
  loadBalancer: {}
