apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: mongodbservice
  name: mongodbservice
spec:
  ports:
  - name: "27017"
    port: 27017
    targetPort: 27017
  selector:
    name: mongodbservice
status:
  loadBalancer: {}
