apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: mysqlservice
  name: mysqlservice
spec:
  type: NodePort
  ports:
  - name: "3306"
    port: 3306
    nodePort: 30043
  selector:
    name: mysqlservice
status:
  loadBalancer: {}
