apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mysqlservice
  name: mysqlservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mysqlservice
  template:
    metadata:
      labels:
        name: mysqlservice
    spec:
      containers:
      - env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: MYSQL_DATABASE
          value: AuthenticationDB
        - name: MYSQL_ROOT_PASSWORD
          value: Global@145#
        - name: MYSQL_USERNAME
          value: root
        image: ashishrits081/mysql:latest
        name: mysql-container
        ports:
        - containerPort: 3306
        resources: {}
      restartPolicy: Always
status: {}
