apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: mysqlservice
  name: mysqlservice
spec:
  ports:
  - name: "3306"
    port: 3306
    targetPort: 3306
  selector:
    name: mysqlservice
status:
  loadBalancer: {}
