apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: paymentservice
  name: paymentservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: paymentservice
  template:
    metadata:
      labels:
        name: paymentservice
    spec:
      containers:
      - image: ashishrits081/paymentservice:latest
        name: payment-service-container
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserversvc.default.svc.cluster.local:8761/eureka
        ports:
        - containerPort: 8089
        resources: {}
      restartPolicy: Always
status: {}
