apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: paymentservice
  name: paymentservice
spec:
  type: NodePort
  ports:
  - name: "8089"
    port: 8089
    nodePort: 30044
  selector:
    name: paymentservice
status:
  loadBalancer: {}
