apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: paymentservice
  name: paymentservice
spec:
  ports:
  - name: "8089"
    port: 8089
    targetPort: 8089
  selector:
    name: paymentservice
status:
  loadBalancer: {}
