apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: paymentservice
  name: paymentservice
spec:
  ports:
  - name: "8070"
    port: 8070
    targetPort: 8070
  selector:
    name: paymentservice
status:
  loadBalancer: {}
