apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: product-webapp
  name: product-webapp
spec:
  ports:
  - name: "8087"
    port: 8087
    targetPort: 8087
  selector:
    name: product-webapp
status:
  loadBalancer: {}
