apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: product-webapp
  name: product-webapp
spec:
  ports:
  - name: "4200"
    port: 4200
    targetPort: 4200
  selector:
    name: product-webapp
status:
  loadBalancer: {}
