apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  type: NodePort
  ports:
  - name: "5672"
    port: 5672
    nodePort: 30046
  - name: "15672"
    port: 15672
    nodePort: 30047
  selector:
    name: rabbitmq
status:
  loadBalancer: {}
