apiVersion: apps/v1
kind: Deployment
metadata:
  
  
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      
      labels:
        name: rabbitmq
    spec:
      containers:
      - image: ashishrits081/rabbitmq:management
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
        resources: {}
      restartPolicy: Always
status: {}
