apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      name: rabbitmq
  template:
    metadata:
      labels:
        name: rabbitmq
    spec:
      containers:
      - image: ashishrits081/rabbitmq:latest
        name: rabbitmq
        ports:
        - containerPort: 5672
        - containerPort: 15672
      restartPolicy: Always
