apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: userservice
  name: userservice
spec:
  ports:
  - name: "8083"
    port: 8083
    targetPort: 8083
  selector:
    name: userservice
status:
  loadBalancer: {}
