apiVersion: v1
kind: Service
metadata:
  
  
  labels:
    name: userservice
  name: userservice
spec:
  ports:
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    name: userservice
status:
  loadBalancer: {}
