apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: userservice
  name: userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      name: userservice
  template:
    metadata:
      labels:
        name: userservice
    spec:
      containers:
      - image: ashishrits081/userservice:latest
        name: user-service-container
        env:
        - name: enthusiast_home_page_url
          value: http://product-webapp.default.svc.cluster.local:8087/#/innovators
        - name: expert_home_page_url
          value: http://product-webapp.default.svc.cluster.local:8087/#/experts
        - name: enthusiast_redirect_url
          value: http://userservice.default.svc.cluster.local:8083/api/v1/authorize/enthusiast/complete
        - name: expert_redirect_url
          value: http://userservice.default.svc.cluster.local:8083/api/v1/authorize/expert/complete
        - name: eureka.client.serviceUrl.defaultZone
          value: http://eurekaserver.default.svc.cluster.local:8761/eureka
        - name: spring.data.mongodb.host
          value: mongodbservice.default.svc.cluster.local
        ports:
        - containerPort: 8083
        resources: {}
      restartPolicy: Always
status: {}
